package com.grahamedgecombe.advent2024.day8

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day8Test {
    @Test
    fun testPart1() {
        assertEquals(14, Day8.solvePart1(TEST_INPUT))
        assertEquals(359, Day8.solvePart1(PROD_INPUT))
    }

    private companion object {
        private val TEST_INPUT = Day8.parse("""
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
        """.trimIndent())
        private val PROD_INPUT = Day8.parse()
    }
}
